### ISSUE TITLE
Color xp notification

### ISSUE THREAD

**Issue by yololetsplay** [Lergin/Laborus#10]
Can u pls add that you can define colors for the notifications?

E.g. `Miner` in green and the `XP` in grey (make it configurable in the config).

```
color_job=§2
color_xp=§7
```

[Color Codes](http://minecraft-de.gamepedia.com/Formatierungscodes)

![2017-03-08_11 49 47](https://cloud.githubusercontent.com/assets/22519816/23701256/5ef30138-03f6-11e7-8537-11b7c8ecb2da.png)

**Comment by Lergin** [comment]
This should also be possible after i have moved all of the messages to the configuration file (yes there are already there but not really usable ;) )

**Comment by yololetsplay** [comment]
I'll take a look at it :P

**Comment by Lergin** [comment]
I will track this in #11

**Comment by Lergin** [comment]
You can now configure that in the config through setting the following setting:

```
translations {
    en {
        "JOB_XP_ACTION_BAR" {
            arguments {
                "job.name" {
                    optional=false
                }
                "job.xp" {
                    optional=false
                }
                "job.xp_for_next_level" {
                    optional=false
                }
            }
            content {
                extra=[
                    {
						color=green
                        text="{job.name}"
                    },
                    {
                        text=": "
                    },
                    {
						color=gray
                        text="{job.xp}"
                    },
                    {
                        text=" / "
                    },
                    {
						color=gray
                        text="{job.xp_for_next_level}"
                    }
                ]
                text=""
            }
            options {
                closeArg="}"
                openArg="{"
            }
        }
    }
}
```

![](http://i.imgur.com/nmHgyc4.png)

**Comment by yololetsplay** [comment]
FANTASTIC MATE!

Can u make it editable too for the `Your level is not high enough` message for each job?
So you could message the player with `You do not know how to use an {item} (e.g. iron_axe) right now`

**Comment by yololetsplay** [comment]
And depending on your translation system:
How do player choose which language they wanna use?

**Comment by Lergin** [comment]
I maybe be able to add  some more parameters to the messages so something like your message can be possible.

The language is the same that is used by minecraft itself and if no translation for that language is there it will fallback to the default language of the server or if also there is no translation for that language to the highest placed language in the config file. By the way i had planned to make the fallback languages configurable.

**Comment by yololetsplay** [comment]
Maybe show all possible parameters in config as an comment :)

**Comment by Lergin** [comment]
I will write them down somewhere most likely in the wiki here on github and on a page on ore :)

**Comment by Lergin** [comment]
They are now available on the [GitHub Pages](https://github.com/Lergin/Laborus/wiki/Translation-Parameters) and on [Sponge Ore](https://ore.spongepowered.org/Lergin/Laborus/pages/Translation%20Parameters)
