### ISSUE TITLE
Custom Messages for translation system

### ISSUE THREAD

**Issue by yololetsplay** [Lergin/Laborus#16]
Can u make it editable too for the `Your level is not high enough` message for each job?
So you could message the player with `You do not know how to use an {item} (e.g. iron_axe) right now`

**Comment by Lergin** [comment]
i added an item parameter to the translation of `JOB_LEVEL_NOT_HIGH_ENOUGH` and with the rest of your message you mean that the message can be configured for each job individually?

**Comment by yololetsplay** [comment]
Ya that's exactly what I mean.
Like I said it in [Issue 10](https://github.com/Lergin/Laborus/issues/10) some seconds ago :)

**Comment by Lergin** [comment]
This has been added as of https://github.com/Lergin/Laborus/commit/65b37ee5415e80a5649756fbf9e2e6166434005a

All Messages that start with `JOB_` can be set for each job through adding of `_jobid` to the end of the key of the translation eg. `JOB_XP_ACTION_BAR_miner` to set a special `JOB_XP_ACTION_BAR` message for the miner job.

**Comment by yololetsplay** [comment]
Fantastic!
