### ISSUE TITLE
Config does not rebuild since update 1.2

### ISSUE THREAD

**Issue by yololetsplay** [Lergin/Laborus#18]
I deleted the conf files bc it's an new system and all, but the config does not setup by itself.
The files `laborus.conf` and `db` creates, but `conf` with 1 empty line in it.

**Comment by Lergin** [comment]
There only should be the `laborus.conf` and the db file the config is filled with the default values after the first stop of the server.

**Comment by yololetsplay** [comment]
I deleted all files again and an `laborus.conf` do not create by itself now.

**Comment by yololetsplay** [comment]
The server got much lags btw after the update. I cannot say way.

**Comment by yololetsplay** [comment]
Also tried to delete the folder not only the files, same problem.
Seems that my system lagged, but still the conf does not create.

**Comment by Lergin** [comment]
I can confirm that the config isn't created I'm currently searching for the reason :)

**Comment by yololetsplay** [comment]
The good thing is that I tested it and not new people just hates ur plugin if they start with 1.2 :P

**Comment by Lergin** [comment]
I found the bug, it should be fixed in the next version that i should release in a few minutes. The file now also gets generated at the start of the server :)

**Comment by Lergin** [comment]
It's out: https://ore.spongepowered.org/Lergin/Laborus/versions/1.2.1
