### ISSUE TITLE
Handle account job levels in file

### ISSUE THREAD

**Issue by yololetsplay** [Lergin/Laborus#19]
To protect the job progresses of the players for upcoming releases it's needed to put them in an file.
I played hours yesterday and now everything got's beaten :D

**Comment by Lergin** [comment]
That shouldn't happen if you haven't played with the Minecraft player files itself in which the data is saved... (And hasn't on my test server ...)

**Comment by yololetsplay** [comment]
Good to know. No I didn't, I just think I can't setup my old miner.conf again?

**Comment by Lergin** [comment]
Oh and the jobid needs to be the same to load the data again.

**Comment by Lergin** [comment]
And no the options of the config have changed a lot so there is a bit of handporting todo

**Comment by yololetsplay** [comment]
Ya I included it now, everything is back :P But better go back to the system to handle jobs in conf-files.

**Comment by Lergin** [comment]
Ah you already created an issue (#20) for that and yes I think that too but I first need to figure out how to simplify implement that :)
