### ISSUE TITLE
Economy value keeps resetting to zero

### ISSUE THREAD

**Issue by XxAshmitxX** [Lergin/Laborus#22]
Hello

Once i setup economy for a job and add min and max amount
then reload or restart server
When I go back and check config the min and max value resets to 0. This happens no matter how many time i keep changing it
here is my miner.conf
had to replace .conf to .txt to be able to upload here
[miner.txt](https://github.com/Lergin/Laborus/files/837989/miner.txt)

**Comment by Lergin** [comment]
Thanks for reporting that bug I just fixed that problem! Also you need to set probability between 0.0 and 1.0 (1.0 is always and 0.5 50% of the time and so on ;) )

**Comment by XxAshmitxX** [comment]
Always here means whenever a player levels up or whenever he breaks blocks?

And thanks for fixing it so quick ^_^

**Comment by Lergin** [comment]
The awards are awarded after an action, so that if you set the actions setting to ["BREAK"] it will only be awarded if a block has been breaked. Otherwise it will happen on each action (including use which already happens if just a mouse button is pressed while holding an item from the use actions.

**Comment by XxAshmitxX** [comment]
oh, ohk thanks ^_^
