### ISSUE TITLE
New plugin, using this system [Talk to Civs, Quests]

### ISSUE THREAD

**Issue by yololetsplay** [Lergin/Laborus#25]
Could you create another plugin where u use ur system, like.
**What you have:**
NPC named Eduard.

**Now you use ur actions system**
```
Use right hand on Eduard, do 
msg Eduard $player Hi my friend.
msg Eduard $player Go get some wood for me.
quests add 1 (ID) $player
```

With `/quests` check for open quests.

**QUESTS:
[1] Eduard: Collect 10 birch wood and bring it to Eduard**

If you bring the stuff to him and use ur hand on him with right click again,
another command runs by server.

Quests should be configurable in conf by ID.

**EDIT:**
There needs to be an check so that you have the stuff in your inventory, like:,
if player has content, do:
```
remove 10 minecraft:(birch wood)
msg Eduard $player Thx for the stuff.
run the commands
```
else:
`msg Eduard $player You do not have the wood for me.`

**Comment by Lergin** [comment]
I generally do not do plugin request but rather create something if i currently feel in the mood of creating something ;) So you may look into [Sponge Ore](https://ore.spongepowered.org/) for such an plugin or create an topic in the [Plugin Request Forum](https://forums.spongepowered.org/c/plugins/plugin-requests) of the Sponge Forums.

**Comment by yololetsplay** [comment]
Thx for ur advice :)
