### ISSUE TITLE
Block JobActions till allowed in all Jobs

### ISSUE THREAD

**Issue by Lergin** [Lergin/Laborus#28]

**Comment by AsylumDreams** [comment]
Just to add some clarification, the issue is that they are blocked until they are unlocked across all jobs, rather than being open when unlocked in one ^_^

**Comment by Lergin** [comment]
I have added another setting to the items (`alsoInOtherJob`) that will activate this check it is deactivated by default because i don't really think that this will happen with that many items and needs a lot of checks to make sure that no other job has it anywhere.
