### ISSUE TITLE
Markers / achievements / events

### ISSUE THREAD

**Issue by AsylumDreams** [Lergin/Laborus#37]
Bit of an odd-one here but something I'm not aware of anyone else doing - how possible would it be to be able to have things triggered by say distance travelled, or damage taken, or acquiring an achievement and so on?

 Not really certain that many / any would want this as a central part of their server, but it'd definitely allow some interesting fluff and story.

**Comment by Lergin** [comment]
I don't really think that something like that has really something to do with jobs and it also can't be represented by the current way i create jobactions so i don't think i will add something like that in the foreseeable future.
