### ISSUE TITLE
API 7

### ISSUE THREAD

**Issue by TooVeryIcey** [Lergin/Laborus#41]
It Does Not Seem To Work With API7 I Get Errors Galore When Running

**Comment by malte-laukoetter** [comment]
Yes that's possible. I currently have some changes already committed that may fix it but I would first need to test it and create a new version. I will do that in about an week as I have an exam on Friday :)

**Comment by TooVeryIcey** [comment]
Awesome! Thanks A Million For The Reply

**Comment by malte-laukoetter** [comment]
I just tested it and everything seems to work so i uploaded a new version to Ore: https://ore.spongepowered.org/Lergin/Laborus/versions/1.5.0
