### ISSUE TITLE
Too long XP message

### ISSUE THREAD

**Issue by yololetsplay** [Lergin/Laborus#5]
Pls limit the amount of numbers after comma.

![2017-03-08_08 51 29](https://cloud.githubusercontent.com/assets/22519816/23694881/a4e35766-03dc-11e7-8d9a-40f71b5af63c.png)

**Comment by Lergin** [comment]
In the next version it will only shows 2 numbers after the comma.

**Comment by yololetsplay** [comment]
Great! Thx :)
