### ISSUE TITLE
Overview buggy

### ISSUE THREAD

**Issue by yololetsplay** [Lergin/Laborus#6]
This is what the overview looks like.
Can u fix it?
Also pls add that you see how much XP is needed for the next level.
Maybe if u mine get the message `Miner 102 | 150 XP` or `Miner 102 of 150 XP`

![2017-03-08_08 57 33](https://cloud.githubusercontent.com/assets/22519816/23695060/b04b563e-03dd-11e7-8e12-dbe64ea4a27b.png)

**Comment by Lergin** [comment]
Apparently Minecraft is pretty bad at tables so i changed a bit more of the format:  

![](http://i.imgur.com/p5gVzfd.png)

**Comment by yololetsplay** [comment]
That looks great!
Does it comes in the upcoming version?

**Comment by Lergin** [comment]
it is already in the version i have released some minutes ago: https://ore.spongepowered.org/Lergin/Laborus/versions/1.1.1

**Comment by yololetsplay** [comment]
Didn't noticed :) Is there any way to support u? Good to know for near future ;)

**Comment by Lergin** [comment]
Just keep reporting bugs if you find some, I'm happy if someone is using my software ;)

**Comment by yololetsplay** [comment]
Could you implement the overview with `xp` and `xp-to-next-level` also for this?

![2017-03-08_11 49 47](https://cloud.githubusercontent.com/assets/22519816/23701125/b181226e-03f5-11e7-8430-b172085d632b.png)

**Comment by Lergin** [comment]
Yes that should be possible, but to make changes like these easier i will rework some of my messaging system first so this can be configured in the config :)

**Comment by Lergin** [comment]
This now can be set in the translation part of the config.

**Comment by yololetsplay** [comment]
We can close this issue.

Can you allow me to close issues by myself for future?

**Comment by Lergin** [comment]
It's already closed :)

**Comment by yololetsplay** [comment]
:D
